export const seedContacts = [
  {
    id: "3d8f2d7f-8e8f-4f8a-9a2f-0f2bc3c9f001",
    firstName: "John",
    lastName: "Smith",
    email: "john.smith@example.com",
    phone: "+1 (613) 555-0101",
    relationship: "Colleague",
    company: "Ottawa Tech Solutions",
    note: "Works in the same dev team, great at backend.",
  },
  {
    id: "3d8f2d7f-8e8f-4f8a-9a2f-0f2bc3c9f002",
    firstName: "Emily",
    lastName: "Johnson",
    email: "emily.johnson@example.com",
    phone: "+1 (613) 555-0102",
    relationship: "Friend",
    company: "Algonquin College",
    note: "Met at Algonquin orientation, same program.",
  },
  {
    id: "3d8f2d7f-8e8f-4f8a-9a2f-0f2bc3c9f003",
    firstName: "Michael",
    lastName: "Brown",
    email: "michael.brown@example.com",
    phone: "+1 (613) 555-0103",
    relationship: "Classmate",
    company: "Algonquin College",
    note: "Group project partner in MTM6404.",
  },
  {
    id: "3d8f2d7f-8e8f-4f8a-9a2f-0f2bc3c9f004",
    firstName: "Sarah",
    lastName: "Davis",
    email: "sarah.davis@example.com",
    phone: "+1 (613) 555-0104",
    relationship: "Family",
    company: "Homemaker",
    note: "Cousin, based in Toronto.",
  },
  {
    id: "3d8f2d7f-8e8f-4f8a-9a2f-0f2bc3c9f005",
    firstName: "David",
    lastName: "Wilson",
    email: "david.wilson@example.com",
    phone: "+1 (613) 555-0105",
    relationship: "Colleague",
    company: "Shopify",
    note: "Mentor from internship, very helpful with React.",
  },
  {
    id: "3d8f2d7f-8e8f-4f8a-9a2f-0f2bc3c9f006",
    firstName: "Jessica",
    lastName: "Taylor",
    email: "jessica.taylor@example.com",
    phone: "+1 (613) 555-0106",
    relationship: "Friend",
    company: "Student",
    note: "Friends since high school, now both in Ottawa.",
  },
];
